apiVersion: v1
kind: Service
metadata:
  name: my-service-np
  labels:
    app: revise1
    env: Dev1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: revise1
    env: Dev1